// Mocks generated by Mockito 5.4.6 from annotations
// in sangrah/test/src/blocs/gallery_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i7;
import 'dart:typed_data' as _i8;
import 'dart:ui' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:photo_manager/photo_manager.dart' as _i3;
import 'package:sangrah/src/services/gallery_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSize_0 extends _i1.SmartFake implements _i2.Size {
  _FakeSize_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_2 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLatLng_3 extends _i1.SmartFake implements _i3.LatLng {
  _FakeLatLng_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAssetEntity_4 extends _i1.SmartFake implements _i3.AssetEntity {
  _FakeAssetEntity_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GalleryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGalleryService extends _i1.Mock implements _i4.GalleryService {
  MockGalleryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.AssetEntity>> getPhotos({
    required int? page,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPhotos, [], {#page: page, #limit: limit}),
            returnValue: _i5.Future<List<_i3.AssetEntity>>.value(
              <_i3.AssetEntity>[],
            ),
          )
          as _i5.Future<List<_i3.AssetEntity>>);
}

/// A class which mocks [AssetEntity].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockAssetEntity extends _i1.Mock implements _i3.AssetEntity {
  MockAssetEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  int get subtype =>
      (super.noSuchMethod(Invocation.getter(#subtype), returnValue: 0) as int);

  @override
  int get typeInt =>
      (super.noSuchMethod(Invocation.getter(#typeInt), returnValue: 0) as int);

  @override
  int get duration =>
      (super.noSuchMethod(Invocation.getter(#duration), returnValue: 0) as int);

  @override
  int get width =>
      (super.noSuchMethod(Invocation.getter(#width), returnValue: 0) as int);

  @override
  int get height =>
      (super.noSuchMethod(Invocation.getter(#height), returnValue: 0) as int);

  @override
  int get orientation =>
      (super.noSuchMethod(Invocation.getter(#orientation), returnValue: 0)
          as int);

  @override
  bool get isFavorite =>
      (super.noSuchMethod(Invocation.getter(#isFavorite), returnValue: false)
          as bool);

  @override
  _i5.Future<String> get titleAsync =>
      (super.noSuchMethod(
            Invocation.getter(#titleAsync),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(this, Invocation.getter(#titleAsync)),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> get titleAsyncWithSubtype =>
      (super.noSuchMethod(
            Invocation.getter(#titleAsyncWithSubtype),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.getter(#titleAsyncWithSubtype),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i3.AssetType get type =>
      (super.noSuchMethod(
            Invocation.getter(#type),
            returnValue: _i3.AssetType.other,
          )
          as _i3.AssetType);

  @override
  bool get isLivePhoto =>
      (super.noSuchMethod(Invocation.getter(#isLivePhoto), returnValue: false)
          as bool);

  @override
  int get orientatedWidth =>
      (super.noSuchMethod(Invocation.getter(#orientatedWidth), returnValue: 0)
          as int);

  @override
  int get orientatedHeight =>
      (super.noSuchMethod(Invocation.getter(#orientatedHeight), returnValue: 0)
          as int);

  @override
  _i2.Size get orientatedSize =>
      (super.noSuchMethod(
            Invocation.getter(#orientatedSize),
            returnValue: _FakeSize_0(this, Invocation.getter(#orientatedSize)),
          )
          as _i2.Size);

  @override
  _i5.Future<_i7.File?> get file =>
      (super.noSuchMethod(
            Invocation.getter(#file),
            returnValue: _i5.Future<_i7.File?>.value(),
          )
          as _i5.Future<_i7.File?>);

  @override
  _i5.Future<_i7.File?> get fileWithSubtype =>
      (super.noSuchMethod(
            Invocation.getter(#fileWithSubtype),
            returnValue: _i5.Future<_i7.File?>.value(),
          )
          as _i5.Future<_i7.File?>);

  @override
  _i5.Future<_i7.File?> get originFile =>
      (super.noSuchMethod(
            Invocation.getter(#originFile),
            returnValue: _i5.Future<_i7.File?>.value(),
          )
          as _i5.Future<_i7.File?>);

  @override
  _i5.Future<_i7.File?> get originFileWithSubtype =>
      (super.noSuchMethod(
            Invocation.getter(#originFileWithSubtype),
            returnValue: _i5.Future<_i7.File?>.value(),
          )
          as _i5.Future<_i7.File?>);

  @override
  _i5.Future<_i8.Uint8List?> get originBytes =>
      (super.noSuchMethod(
            Invocation.getter(#originBytes),
            returnValue: _i5.Future<_i8.Uint8List?>.value(),
          )
          as _i5.Future<_i8.Uint8List?>);

  @override
  _i5.Future<_i8.Uint8List?> get thumbnailData =>
      (super.noSuchMethod(
            Invocation.getter(#thumbnailData),
            returnValue: _i5.Future<_i8.Uint8List?>.value(),
          )
          as _i5.Future<_i8.Uint8List?>);

  @override
  Duration get videoDuration =>
      (super.noSuchMethod(
            Invocation.getter(#videoDuration),
            returnValue: _FakeDuration_1(
              this,
              Invocation.getter(#videoDuration),
            ),
          )
          as Duration);

  @override
  _i2.Size get size =>
      (super.noSuchMethod(
            Invocation.getter(#size),
            returnValue: _FakeSize_0(this, Invocation.getter(#size)),
          )
          as _i2.Size);

  @override
  DateTime get createDateTime =>
      (super.noSuchMethod(
            Invocation.getter(#createDateTime),
            returnValue: _FakeDateTime_2(
              this,
              Invocation.getter(#createDateTime),
            ),
          )
          as DateTime);

  @override
  DateTime get modifiedDateTime =>
      (super.noSuchMethod(
            Invocation.getter(#modifiedDateTime),
            returnValue: _FakeDateTime_2(
              this,
              Invocation.getter(#modifiedDateTime),
            ),
          )
          as DateTime);

  @override
  _i5.Future<bool> get exists =>
      (super.noSuchMethod(
            Invocation.getter(#exists),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<String?> get mimeTypeAsync =>
      (super.noSuchMethod(
            Invocation.getter(#mimeTypeAsync),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<_i3.AssetEntity?> obtainForNewProperties() =>
      (super.noSuchMethod(
            Invocation.method(#obtainForNewProperties, []),
            returnValue: _i5.Future<_i3.AssetEntity?>.value(),
          )
          as _i5.Future<_i3.AssetEntity?>);

  @override
  _i5.Future<int> durationWithOptions({bool? withSubtype = false}) =>
      (super.noSuchMethod(
            Invocation.method(#durationWithOptions, [], {
              #withSubtype: withSubtype,
            }),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<bool> isLocallyAvailable({
    bool? isOrigin = false,
    bool? withSubtype = false,
    _i3.PMDarwinAVFileType? darwinFileType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isLocallyAvailable, [], {
              #isOrigin: isOrigin,
              #withSubtype: withSubtype,
              #darwinFileType: darwinFileType,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.LatLng> latlngAsync() =>
      (super.noSuchMethod(
            Invocation.method(#latlngAsync, []),
            returnValue: _i5.Future<_i3.LatLng>.value(
              _FakeLatLng_3(this, Invocation.method(#latlngAsync, [])),
            ),
          )
          as _i5.Future<_i3.LatLng>);

  @override
  _i5.Future<_i7.File?> loadFile({
    bool? isOrigin = true,
    bool? withSubtype = false,
    _i3.PMProgressHandler? progressHandler,
    _i3.PMDarwinAVFileType? darwinFileType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadFile, [], {
              #isOrigin: isOrigin,
              #withSubtype: withSubtype,
              #progressHandler: progressHandler,
              #darwinFileType: darwinFileType,
            }),
            returnValue: _i5.Future<_i7.File?>.value(),
          )
          as _i5.Future<_i7.File?>);

  @override
  _i5.Future<_i8.Uint8List?> thumbnailDataWithSize(
    _i3.ThumbnailSize? size, {
    _i3.ThumbnailFormat? format = _i3.ThumbnailFormat.jpeg,
    int? quality = 100,
    _i3.PMProgressHandler? progressHandler,
    int? frame = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #thumbnailDataWithSize,
              [size],
              {
                #format: format,
                #quality: quality,
                #progressHandler: progressHandler,
                #frame: frame,
              },
            ),
            returnValue: _i5.Future<_i8.Uint8List?>.value(),
          )
          as _i5.Future<_i8.Uint8List?>);

  @override
  _i5.Future<_i8.Uint8List?> thumbnailDataWithOption(
    _i3.ThumbnailOption? option, {
    _i3.PMProgressHandler? progressHandler,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #thumbnailDataWithOption,
              [option],
              {#progressHandler: progressHandler},
            ),
            returnValue: _i5.Future<_i8.Uint8List?>.value(),
          )
          as _i5.Future<_i8.Uint8List?>);

  @override
  _i5.Future<String?> getMediaUrl({_i3.PMProgressHandler? progressHandler}) =>
      (super.noSuchMethod(
            Invocation.method(#getMediaUrl, [], {
              #progressHandler: progressHandler,
            }),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i3.AssetEntity copyWith({
    String? id,
    int? typeInt,
    int? width,
    int? height,
    int? duration,
    int? orientation,
    bool? isFavorite,
    String? title,
    int? createDateSecond,
    int? modifiedDateSecond,
    String? relativePath,
    double? latitude,
    double? longitude,
    String? mimeType,
    int? subtype,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #id: id,
              #typeInt: typeInt,
              #width: width,
              #height: height,
              #duration: duration,
              #orientation: orientation,
              #isFavorite: isFavorite,
              #title: title,
              #createDateSecond: createDateSecond,
              #modifiedDateSecond: modifiedDateSecond,
              #relativePath: relativePath,
              #latitude: latitude,
              #longitude: longitude,
              #mimeType: mimeType,
              #subtype: subtype,
            }),
            returnValue: _FakeAssetEntity_4(
              this,
              Invocation.method(#copyWith, [], {
                #id: id,
                #typeInt: typeInt,
                #width: width,
                #height: height,
                #duration: duration,
                #orientation: orientation,
                #isFavorite: isFavorite,
                #title: title,
                #createDateSecond: createDateSecond,
                #modifiedDateSecond: modifiedDateSecond,
                #relativePath: relativePath,
                #latitude: latitude,
                #longitude: longitude,
                #mimeType: mimeType,
                #subtype: subtype,
              }),
            ),
          )
          as _i3.AssetEntity);
}
